x-airflow-env: &airflow-env
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
  AIRFLOW__CORE__LOAD_EXAMPLES: "false"
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
  AIRFLOW__LOGGING__LOGGING_LEVEL: INFO
  # Use new section to avoid deprecation warnings:
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow_user:airflow_pass@postgres:5432/airflow
  PYTHONPATH: /opt/airflow:/opt/airflow/src

services:
  airflow-init:
    image: apache/airflow:2.10.2
    environment:
      <<: *airflow-env
      _PIP_ADDITIONAL_REQUIREMENTS: "yfinance pandas pyarrow psycopg2-binary"
    user: "50000:0"
    entrypoint: /bin/bash
    command: >
      -c "airflow db migrate &&
          airflow users create --role Admin --username admin --password admin --email admin@example.com --firstname Admin --lastname User || true"
    volumes:
      - ../dags:/opt/airflow/dags
      - ../logs:/opt/airflow/logs
      - ../plugins:/opt/airflow/plugins
      - ../src:/opt/airflow/src
      - ../stocks:/opt/airflow/stocks        
      - ../data:/opt/airflow/data 
    networks: [yf_net]
    restart: "no"

  airflow-webserver:
    image: apache/airflow:2.10.2
    environment:
      <<: *airflow-env
      _PIP_ADDITIONAL_REQUIREMENTS: "yfinance pandas pyarrow psycopg2-binary"
    command: webserver
    ports: ["8080:8080"]
    user: "50000:0"
    volumes:
      - ../dags:/opt/airflow/dags
      - ../logs:/opt/airflow/logs
      - ../plugins:/opt/airflow/plugins
      - ../src:/opt/airflow/src
      - ../stocks:/opt/airflow/stocks        
      - ../data:/opt/airflow/data 
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks: [yf_net]
    restart: unless-stopped

  airflow-scheduler:
    image: apache/airflow:2.10.2
    environment:
      <<: *airflow-env
      _PIP_ADDITIONAL_REQUIREMENTS: "yfinance pandas pyarrow psycopg2-binary"
    command: scheduler
    user: "50000:0"
    volumes:
      - ../dags:/opt/airflow/dags
      - ../logs:/opt/airflow/logs
      - ../plugins:/opt/airflow/plugins
      - ../src:/opt/airflow/src
      - ../stocks:/opt/airflow/stocks        
      - ../data:/opt/airflow/data 
    networks: [yf_net]
    restart: unless-stopped

networks:
  yf_net:
    external: true
